name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run query
        id: run-query 
        run: |
          mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam -A < query.sql        

      - name: Write query output
        uses: DamianReeves/write-file-action@master
        with:
          path: query-result
          contents: ${{ steps.run-query.outputs.stdout }}
          write-mode: overwrite
      
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'
