name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run query
        run: |
          mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam -A < query.sql        
