name: CI

on:
  push:
    paths:
    - 'query.sql'
  workflow_dispatch:

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run query
        id: run-query 
        run: |
          mysql --user ${{ vars.RFAM_USER }} --host ${{ vars.RFAM_HOST }} --port 4497 --database Rfam -A < query.sql 2>result 1>result
        continue-on-error: true
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
